%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/crich/gitrepos/pgraph/hw2/Problem4/data/dataset.dat
%
% Auto-generated by MATLAB on 16-Jun-2019 01:43:40

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "Outcomes";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dataset = readtable("/Users/crich/gitrepos/pgraph/hw2/Problem4/data/dataset.dat", opts);


%% Clear temporary variables
clear opts

outcomes = dataset.Outcomes;

% create tables of outcomes for each condition distr
p0_totals = zeros(1,2);
p1_0_totals = zeros(2,2);
p2_totals = zeros(1,2);
p3_0_totals = zeros(2,2);
p4_0_totals = zeros(2,2);
p5_134_totals = zeros(8,2);
p6_24_totals = zeros(4,2);
p7_13_totals = zeros(4,2);
p8_134_totals = zeros(8,2);
p9_134_totals = zeros(8,2);
p10_2_totals = zeros(2,2);
p11_124_totals = zeros(8,2);

for i=1:length(outcomes)
    asgn = outcome_to_assignments(outcomes(1234));
    asgnCell = num2cell(asgn);
    [x11, x10, x9, x8, x7, x6, x5, x4, x3, x2, x1, x0] = asgnCell{:};

    % increment each total at the corresponding index
    p0_totals(1, x0 + 1) = p0_totals(1, x0 + 1) + 1;
    p1_0_totals(x0 + 1, x1 + 1) = p1_0_totals(x0 + 1, x1 + 1) + 1;
    p2_totals(1, x2 + 1) = p2_totals(1, x2 + 1) + 1;
    p3_0_totals(x0 + 1, x3 + 1) = p3_0_totals(x0 + 1, x3 + 1) + 1;
    p4_0_totals(x0 + 1, x4 + 1) = p4_0_totals(x0 + 1, x4 + 1) + 1;
    p5_134_totals(x1 + 2*x3 + 4*x4 + 1, x5 + 1) = p5_134_totals(x1 + 2*x3 + 4*x4 + 1, x5 + 1) + 1;
    p6_24_totals(x2 + 2*x4 + 1, x6 + 1) = p6_24_totals(x2 + 2*x4 + 1, x6 + 1) + 1;
    p7_13_totals(x1 + 2*x3 + 1, x7 + 1) = p7_13_totals(x1 + 2*x3 + 1, x7 + 1) + 1;
    p8_134_totals(x1 + 2*x3 + 4*x4 + 1, x8 + 1) = p8_134_totals(x1 + 2*x3 + 4*x4 + 1, x8 + 1) + 1;
    p9_134_totals(x1 + 2*x3 + 4*x4 + 1, x9 + 1) = p9_134_totals(x1 + 2*x3 + 4*x4 + 1, x9 + 1) + 1;
    p10_2_totals(x2 + 1, x10 + 1) = p10_2_totals(x2 + 1, x10 + 1) + 1;
    p11_124_totals(x1 + 2*x2 + 4*x4 + 1, x11 + 1) = p11_124_totals(x1 + 2*x2 + 4*x4 + 1, x11 + 1) + 1;
end

%p11_124_params = bsxfun(@rdivide,p11_124_params,sum(p11_124_params,2));
